In [1]:
import torch
import numpy as np

In [5]:
label=np.empty(50,dtype=np.int32)
label.fill(-1)

In [6]:
label

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [16]:
data=np.random.rand(10,10)

bupt=data[[1,4],[2,3,4]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [15]:
bupt

array([0.30027871, 0.60587165])

In [23]:
temp=np.arange(10)
args=[1,0,3,1,0]
temp[args]

array([1, 0, 3, 1, 0])

In [26]:
ret = np.empty(32)

In [37]:
type(ret.shape)

tuple

In [29]:
data=slice(0,4,2)

In [31]:
type(data)

slice

In [34]:
temp[data]

array([0, 2])